spring:
  spreadsheet:
    id: 1ojNfksTD6GzD6pA_rOEFVex0C2kZqn0GdVY3ltnUFhw
  token:
    directory:
      path: TOKEN_path
  credentials:
    file:
      path: FILE_PATH
  application:
    name: sheets
  oauth2:
    google:
      clientId: CLIENT_ID
      clientSecret: CLIENT_SECRET
